### ISSUE TITLE
NOI maps web component on the Web Component store

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-maps-noi#1]
As a PM I want to have the new NOI maps web component online.

**Comment by Piiit** [comment]
@bertolla Why is this blocked?

**Comment by Piiit** [comment]
Related to https://github.com/noi-techpark/webcomp-maps-noi/pull/2

**Comment by bertolla** [comment]
Peter there was no pull-request till yesterday evening. I started to work this afternoon on this. Wilsch du mi stressn?

**Comment by Piiit** [comment]
No, why? I just wanted to know if this blocking is due to a store issue?

**Comment by bertolla** [comment]
@sseppi 
Webcomponent is now online @ https://webcomponents.opendatahub.testingmachine.eu/webcomponent/9232cce6-2f39-11eb-adc1-0242ac120002
Languages are not working, seems to me. Please test it for the rest.

**Comment by bertolla** [comment]
ok i found out why. Documentation was wrong. language instead of lang

**Comment by sseppi** [comment]
@bertolla 
It seems that everything is working as expected but the formatting it is not the right one. I think it is better to wait to go on production as soon as Cima provides us the new version with the right css.

**Comment by bertolla** [comment]
It's not like they put the wrong one, it's just that they put only minimal css in the resulting webcomponent, so maybe they need to put more.

**Comment by bertolla** [comment]
@Piiit Just now I wanted to release the webcomponent on production, fixed the tags, applied origin to repo, but could not find the production pipeline of this one: https://jenkins.testingmachine.eu/job/it.bz.opendatahub.webcomponents-store/job/webcomp.test-deploy
Is there a reason or is it just missing?

**Comment by Piiit** [comment]
@bertolla This pipeline is for internal testing purposes so I thought that we do not need a production pipeline for it... but if you think it could be useful, I can create one... Let me know
